app/routes/session.py
from flask import Blueprint, current_app, redirect, url_for, flash, session, request
import pymysql
import bcrypt

session_routes = Blueprint('session', __name__)

# Obtener la conexión a la base de datos
connection = current_app.get_db_connection()


@session_routes.route('/login/', methods=['POST'])
def login():
    connection = current_app.get_db_connection()
    try:
        email = request.form['email']
        password = request.form['password']

        with connection.cursor() as cursor:
            # Buscar en la tabla de admin
            cursor.execute("SELECT * FROM admin WHERE email = %s", (email,))
            login_admin = cursor.fetchone()
            if login_admin and password:
                session['email'] = email
                return redirect(url_for('admin.admin'))

        with connection.cursor() as cursor:
            # Buscar en la tabla de users
            cursor.execute("SELECT * FROM user WHERE email = %s", (email,))
            login_user = cursor.fetchone()
            if login_user and bcrypt.checkpw(password.encode('utf-8'), login_user['password']):
                session['email'] = email
                return redirect(url_for('user.user'))

        flash('Correo o contraseña incorrectos')
        return redirect(url_for('main.index'))
    except pymysql.MySQLError as err:
        print(f"Error al iniciar sesión: {err.args[0]}, {err.args[1]}")
        flash('Hubo un error al iniciar sesión. Inténtalo de nuevo.')
        return redirect(url_for('main.index'))


# Ruta para cerrar sesión
@session_routes.route('/logout/')
def logout():
    session.clear()  # Elimina todas las variables de sesión
    return redirect(url_for('main.index'))

app/routes/user.py
from flask import Blueprint, current_app, render_template, url_for, redirect, session, request, flash, make_response, jsonify
from pymysql.cursors import DictCursor
from xhtml2pdf import pisa
from io import BytesIO
import pymysql
import base64

user_routes = Blueprint('user', __name__)

# Obtener la conexión a la base de datos
connection = current_app.get_db_connection()


def get_user(email):
    connection = current_app.get_db_connection()
    if connection:
        try:
            with connection.cursor() as cursor:
                cursor.execute(
                    "SELECT * FROM user WHERE email = %s", (email,))
                user = cursor.fetchone()
                return user
        except pymysql.MySQLError as err:
            print(f"Error al obtener administrador: {err.args[0]}, {err.args[1]}")
    return None


# Ruta para inicio de usuarios
@user_routes.route('/user/')
def user():
    if 'email' in session:
        email = session['email']
        # Función para obtener datos del usuario desde la d
        user = get_user(email)
        if user:
            return render_template('user.html', user=user)
    else:
        return redirect(url_for('main.index'))


@user_routes.route('/user/area/')
def area():
    if 'email' in session:
        email = session['email']
        # Función para obtener datos del usuario desde bd
        user = get_user(email)
        if user:
            return render_template('area.html')
    else:
        return redirect(url_for('main.index'))


@user_routes.route('/RegistrarArea/', methods=['GET', 'POST'])
def RegistrarArea():
    if 'email' in session:
        email = session['email']
        user = get_user(email)
        if user:
            if request.method == 'POST':
                connection = current_app.get_db_connection()
                try:
                    nombre_area = request.form['nombre_area']

                    with connection.cursor() as cursor:
                        # Verificar si el área ya existe en la base de datos para este usuario
                        cursor.execute(
                            "SELECT * FROM areas WHERE NombreArea = %s AND id = %s",
                            (nombre_area, user['id'])
                        )
                        existearea = cursor.fetchone()

                        if existearea is None:
                            sql = "INSERT INTO areas (NombreArea, id) VALUES (%s, %s)"
                            cursor.execute(sql, (nombre_area, user['id']))
                            connection.commit()
                            flash('Se registró el área correctamente')
                        else:
                            flash('El área ya existe')
                        return redirect(url_for('user.area'))

                except pymysql.MySQLError as err:
                    print("Error al registrar área:", err)
                    connection.rollback()
                finally:
                    connection.close()
        else:
            return redirect(url_for('main.index'))
    return redirect(url_for('user.area'))


# Función para obtener las áreas del usuario disponibles desde la base de datos.
def obtener_areas(usuario_id):
    connection = current_app.get_db_connection()
    try:
        with connection.cursor() as cursor:
            query = """
            SELECT IdArea, NombreArea
            FROM areas
            WHERE id = %s
            """
            cursor.execute(query, (usuario_id,))
            areas = cursor.fetchall()
            return areas
    except pymysql.MySQLError as err:
        print(f"Error al obtener áreas desde la base de datos: {err}")
        return []
    finally:
        connection.close()

# Ruta para ingresar un departamento en un área
@user_routes.route('/departamento/', methods=['GET', 'POST'])
def departamento():
    if 'email' in session:
        email = session['email']
        # Función para obtener detalles del usuario desde desde bd
        user = get_user(email)

        if user:
            if request.method == 'POST':

                connection = current_app.get_db_connection()

                try:
                    nombre_departamento = request.form['nombre_departamento']
                    id_area = request.form['id_area']

                    with connection.cursor() as cursor:
                        # Verificar si el departamento ya existe en la misma área
                        cursor.execute("""
                            SELECT * FROM departamento 
                            WHERE NombreDepartamento = %s AND IdArea = %s AND id = %s
                        """, (nombre_departamento, id_area, user['id']))
                        existedepto = cursor.fetchone()

                        if existedepto is None:
                            # Insertar el departamento en la base de datos
                            sql = "INSERT INTO departamento (NombreDepartamento, IdArea, id) VALUES (%s, %s, %s)"
                            cursor.execute(
                                sql, (nombre_departamento, id_area, user['id']))
                            connection.commit()
                            flash('Se registró el departamento correctamente', 'success')
                        else:
                            flash('El departamento ya existe en esta área', 'warning')

                        return redirect(url_for('user.departamento'))

                except pymysql.MySQLError as err:
                    print("Error al registrar departamento:", err)
                    connection.rollback()
                finally:
                    cursor.close()

            usuario_id = user['id']

            # Obtener áreas disponibles utilizando la función obtener_areas()
            areas = obtener_areas(usuario_id)

            return render_template('departamento.html', areas=areas, user=user)
        else:
            # Redirigir si no hay sesión
            return redirect(url_for('main.index'))


def obtener_departamentos(usuario_id):
    """Función para obtener los departamentos del usuario disponibles desde la base de datos."""
    connection = current_app.get_db_connection()
    try:
        with connection.cursor() as cursor:
            query = """
            SELECT IdDepartamento, NombreDepartamento
            FROM departamento
            WHERE id = %s
            """
            cursor.execute(query, (usuario_id,))
            departamentos = cursor.fetchall()
            print("Departamentos obtenidos:", departamentos)  # Debug
            return departamentos
    except pymysql.MySQLError as err:
        print(f"Error al obtener departamentos desde la base de datos: {err}")
        return []


def obtener_puestos(usuario_id):
    connection = current_app.get_db_connection()
    try:
        with connection.cursor() as cursor:
            query = """
            SELECT IdPuesto, NombrePuesto
            FROM puestos
            WHERE DepartamentoId IN (
                SELECT IdDepartamento
                FROM departamento
                WHERE id = %s
            )
            """
            cursor.execute(query, (usuario_id,))
            puestos = cursor.fetchall()
            print("Puestos obtenidos:", puestos)  # Debug
            return puestos
    except pymysql.MySQLError as err:
        print(f"Error al obtener puestos desde la base de datos: {err}")
        return []


@user_routes.route('/puesto/', methods=['GET', 'POST'])
def puesto():
    if 'email' not in session:
        return redirect(url_for('main.index'))

    email = session['email']
    user = get_user(email)
    if not user:
        return redirect(url_for('main.index'))

    if request.method == 'POST':
        connection = current_app.get_db_connection()

        # Obtener datos del formulario
        nombre_puesto = request.form.get('nombre_puesto')
        id_departamento = request.form.get('id_departamento')
        jefe = request.form.get('jefe')
        clave = request.form.get('clave')
        no_plazas = request.form.get('no_plazas')
        objetivo = request.form.get('objetivo')
        reemplaza = request.form.get('reemplaza')
        reemplazado = request.form.get('reemplazado')
        nota = request.form.get('nota')

        equipo_trabajo = request.form.get('equipo_trabajo')
        equipo_lista = [r.strip() for r in equipo_trabajo.split(
            ',')] if equipo_trabajo else []  # Convertir a lista
        equipo_str = ','.join(equipo_lista)  # Convertir a cadena

        fecha = request.form.get('fecha')

        # Captura del campo Relaciones
        relaciones = request.form.get('Relaciones')
        relaciones_lista = [r.strip() for r in relaciones.split(
            ',')] if relaciones else []  # Convertir a lista
        relaciones_str = ','.join(relaciones_lista)  # Convertir a cadena

        # Captura del campo funciones
        funciones = request.form.get('Funciones')
        funciones_lista = [r.strip() for r in funciones.split(
            ',')] if funciones else []  # Convertir a lista
        funciones_str = ','.join(funciones_lista)  # Convertir a cadena

        edad = request.form.get('edad')
        sexo = request.form.get('sexo')
        estado_civil = request.form.get('estado_civil')
        experiencia = request.form.get('experiencia')
        escolaridad = request.form.get('escolaridad')

        # Captura del campo conocimientos
        conocimientos = request.form.get('conocimientos')
        conocimientos_lista = [r.strip() for r in conocimientos.split(
            ',')] if conocimientos else []  # Convertir a lista
        conocimientos_str = ','.join(conocimientos_lista)  # Convertir a cadena

        esfuerzo_fisico = request.form.get('esfuerzo_fisico')
        esfuerzo_mental = request.form.get('esfuerzo_mental')
        riesgo_accidente = request.form.get('riesgo_accidente')
        ambiente = request.form.get('ambiente')
        

app/templates/area.html
<!DOCTYPE html>
<html lang="es">

<head>
	<meta charset="utf-8">
	<meta content="width=device-width, initial-scale=1.0" name="viewport">
	<title>Ánalisis de Puestos</title>
	<meta content="" name="description">
	<meta content="" name="keywords">

	<!-- Favicons -->
	<link href="{{ url_for('static', filename='img/favicon.ico') }}" rel="icon">
	<link href="{{ url_for('static', filename='img/apple-touch-icon.png') }}" rel="apple-touch-icon">

	<!-- Fonts -->
	<link href="https://fonts.googleapis.com" rel="preconnect">
	<link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
	<link
		href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
		rel="stylesheet">

	<!-- Vendor CSS Files -->
	<link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='vendor/aos/aos.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='vendor/glightbox/css/glightbox.min.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='vendor/swiper/swiper-bundle.min.css') }}" rel="stylesheet">

	<!-- Main CSS File -->
	<link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
</head>

<body class="index-page">
	<header id="header" class="header d-flex align-items-center sticky-top">
		<div class="container-fluid container-xl position-relative d-flex align-items-center">

			<a href="{{ url_for('user.user') }}" class="logo d-flex align-items-center me-auto">
				<!-- Uncomment the line below if you also wish to use an image logo -->
				<!-- <img src="assets/img/logo.png" alt=""> -->
				<h1 class="sitename">Usuario</h1>
			</a>

			<nav id="navmenu" class="navmenu">
				<ul>
					<li><a href="{{ url_for('user.user') }}" class="active">Home</a></li>
					<li class="dropdown"><a href="#"><span>Agregar</span> <i
								class="bi bi-chevron-down toggle-dropdown"></i></a>
						<ul>
							<li><a href="{{ url_for('user.area') }}">Área</a></li>
							<li><a href="{{ url_for('user.departamento') }}">Departamento</a></li>
							<li><a href="{{ url_for('user.puesto') }}">Puesto</a></li>
						</ul>
					</li>
					<li class="dropdown"><a href="#"><span>Lista</span> <i
						class="bi bi-chevron-down toggle-dropdown"></i></a>
				<ul>
					<li><a href="{{ url_for('user.areas') }}">Área</a></li>
					<li><a href="{{ url_for('user.mostrarDepartamentos') }}">Departamento</a></li>
					<li><a href="{{ url_for('user.mostrarPuestos') }}">Puesto</a></li>
				</ul>
			</li>
				</ul>
				<i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
			</nav>

			<a class="btn-getstarted" href="{{ url_for('session.logout') }}">Cerrar Sesión</a>

		</div>
	</header>

	<!-- Main Content -->
	<main class="main">
		<!-- Hero Section -->
		<section id="hero" class="section hero">
			<div class="container">
				<div class="small-card">
					<div class="card-header text-center mt-4">
						<h1>Agregar Área</h1>
					</div>
					<div class="card-body text-center mt-2">
						<!-- Flash Messages -->
						{% with messages = get_flashed_messages() %}
						{% if messages %}
						<div class="alert-container">
							{% for message in messages %}
							<div class="alert alert-info alert-dismissible fade show  text-center" role="alert">
								<p>{{ message }}</p>
							</div>
							{% endfor %}
						</div>
						{% endif %}
						{% endwith %}					
						<!-- Formulario de Registro -->
						<form action="/RegistrarArea/" method="post">
							<div class="mb-3">
								<label for="nombre_departamento" class="form-label">Nombre del Área:</label>
								<input type="text" id="nombre_area" name="nombre_area" class="form-control estilo-input" required>
							</div>
							<button type="submit" class="btn btn-block boton">Agregar</button>
						</form>
					</div>
				</div>
			</div>

		</section>
		<!-- /Hero Section -->

	</main>

	<footer id="footer" class="footer position-relative">
        <div class="container footer-top">
            <div class="row gy-4">
                <div class="col-lg-4 col-md-4 footer-about">
                    <a href="index.html" class="d-flex align-items-center">
                        <span class="sitename">Universidad Tecnológica de Acapulco</span>
                    </a>
                    <div class="footer-contact pt-3">
                        <p>Av. Comandante Bouganville L5</p>
                        <p>Fracc. Lomas de Costa Azul C.P. 39830, Acapulco de Juarez, GRO</p>
                    </div>
                </div>

                <div class="col-lg-4 col-md-4 footer-links">
                    <h4>Links útiles</h4>
                    <ul>
                        <li><i class="bi bi-chevron-right"></i> <a href="{{ url_for('user.user') }}">Home</a></li>
                        <li><i class="bi bi-chevron-right"></i> <a href="https://utacapulco.edu.mx/">Universidad</a></li>
						<p class="mt-3"><strong>Phone:</strong> <span>7446886416</span></p>
                        <p><strong>Email:</strong> <span>universidad@utacapulco.edu.mx</span></p>
                    </ul>
                </div>

                <div class="col-lg-4 col-md-4">
                    <h4>Síguenos</h4>
                    <p>Sigue nuestras redes sociales para estar al tanto de las últimas noticias y eventos. Conéctate con nosotros en Facebook e Instagram </p>
                    <div class="social-links d-flex">
                        <a href="https://www.facebook.com/p/Oficial-Universidad-Tecnol%C3%B3gica-de-Acapulco-100063862541593/?locale=es_LA"><i class="bi bi-facebook"></i></a>
                        <a href="https://www.instagram.com/utacapulco/"><i class="bi bi-instagram"></i></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="container copyright text-center mt-4">
            <p>© <span>Copyright</span> <strong class="px-1 sitename">UTA</strong> <span>Todos los derechos reservados</span></p>
        </div>
    </footer>

	<!-- Scroll Top -->
	<a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i
			class="bi bi-arrow-up-short"></i></a>

	<!-- Vendor JS Files -->
	<script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
	<script src="{{ url_for('static', filename='vendor/php-email-form/validate.js') }}"></script>
	<script src="{{ url_for('static', filename='vendor/aos/aos.js') }}"></script>
	<script src="{{ url_for('static', filename='vendor/glightbox/js/glightbox.min.js') }}"></script>
	<script src="{{ url_for('static', filename='vendor/imagesloaded/imagesloaded.pkgd.min.js') }}"></script>
	<script src="{{ url_for('static', filename='vendor/isotope-layout/isotope.pkgd.min.js') }}"></script>
	<script src="{{ url_for('static', filename='vendor/swiper/swiper-bundle.min.js') }}"></script>

	<!-- Main JS File -->
	<script src="{{ url_for('static', filename='js/main.js') }}"></script>

</body>

</html>

app/templates/botones.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Actividad</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <style>
      body {
        background-color: black;
        color: white;
      }
    </style>
  </head>
  <body>
    <div class="container text-center py-5">
      <div class="row">
        <div class="col-md-4 mb-3">
          <button class="btn btn-success w-100">Confirmar</button>
        </div>
        <div class="col-md-4 mb-3">
          <button class="btn btn-warning text-white w-100">Alerta</button>
        </div>
        <div class="col-md-4 mb-3">
          <button class="btn btn-danger w-100">Error</button>
        </div>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/templates/departamento.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Análisis de Puestos</title>
    <meta name="description" content="">
    <meta name="keywords" content="">

    <!-- Favicons -->
    <link rel="icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
    <link rel="apple-touch-icon" href="{{ url_for('static', filename='img/apple-touch-icon.png') }}">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700&family=Raleway:wght@100;200;300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/aos/aos.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/glightbox/css/glightbox.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/swiper/swiper-bundle.min.css') }}" rel="stylesheet">

    <!-- Main CSS File -->
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
</head>

<body class="index-page">

    <!-- Header -->
    <header id="header" class="header d-flex align-items-center sticky-top">
        <div class="container-fluid container-xl position-relative d-flex align-items-center">

            <a href="{{ url_for('user.user') }}" class="logo d-flex align-items-center me-auto">
                <!-- Uncomment the line below if you also wish to use an image logo -->
                <!-- <img src="assets/img/logo.png" alt=""> -->
                <h1 class="sitename">Usuario</h1>
            </a>

            <nav id="navmenu" class="navmenu">
                <ul>
                    <li><a href="{{ url_for('user.user') }}" class="active">Home</a></li>
                    <li class="dropdown"><a href="#"><span>Agregar</span> <i
                                class="bi bi-chevron-down toggle-dropdown"></i></a>
                        <ul>
                            <li><a href="{{ url_for('user.area') }}">Área</a></li>
                            <li><a href="{{ url_for('user.departamento') }}">Departamento</a></li>
                            <li><a href="{{ url_for('user.puesto') }}">Puesto</a></li>
                        </ul>
                    </li>
                    <li class="dropdown"><a href="#"><span>Lista</span> <i
                                class="bi bi-chevron-down toggle-dropdown"></i></a>
                        <ul>
                            <li><a href="{{ url_for('user.areas') }}">Área</a></li>
                            <li><a href="{{ url_for('user.mostrarDepartamentos') }}">Departamento</a></li>
                            <li><a href="{{ url_for('user.mostrarPuestos') }}">Puesto</a></li>
                        </ul>
                    </li>
                </ul>
                <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
            </nav>

            <a class="btn-getstarted" href="{{ url_for('session.logout') }}">Cerrar Sesión</a>

        </div>
    </header>
    <!-- End Header -->

    <!-- Main Content -->
    <main class="main">
        <!-- Hero Section -->
        <section id="hero" class="section hero">
            <div class="container">
                <div class="small-card">
                    <div class="card-header text-center mt-4">
                        <h1>Agregar Departamento</h1>
                    </div>
                    <div class="card-body text-center mt-2">
                        <!-- Flash Messages -->
                        {% with messages = get_flashed_messages() %}
                        {% if messages %}
                        <div class="alert-container">
                            {% for message in messages %}
                            <div class="alert alert-info alert-dismissible fade show  text-center" role="alert">
                                <p>{{ message }}</p>
                            </div>
                            {% endfor %}
                        </div>
                        {% endif %}
                        {% endwith %}
                        <!-- Formulario de Registro -->
                        <form action="/departamento/" method="post" class="form-horizontal">
                            <div class="mb-3">
                                <label for="nombre_departamento" class="form-label">Nombre del Departamento:</label>
                                <input type="text" id="nombre_departamento" name="nombre_departamento"
                                    class="form-control" required>
                            </div>

                            <div class="mb-3">
                                <label for="id_area" class="form-label">Área:</label>
                                <select id="id_area" name="id_area" class="form-select" required>
                                    {% for area in areas %}
                                    <option value="{{ area.IdArea }}">{{ area.NombreArea }}</option>
                                    {% endfor %}
                                </select>
                            </div>

                            <button type="submit" class="btn btn-block boton">Agregar</button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!-- End Hero Section -->
    </main>
    <!-- End Main Content -->

    <!-- Footer -->
    <footer id="footer" class="footer position-relative">
        <div class="container footer-top">
            <div class="row gy-4">
                <div class="col-lg-4 col-md-4 footer-about">
                    <a href="index.html" class="d-flex align-items-center">
                        <span class="sitename">Universidad Tecnológica de Acapulco</span>
                    </a>
                    <div class="footer-contact pt-3">
                        <p>Av. Comandante Bouganville L5</p>
                        <p>Fracc. Lomas de Costa Azul C.P. 39830, Acapulco de Juarez, GRO</p>
                    </div>
                </div>

                <div class="col-lg-4 col-md-4 footer-links">
                    <h4>Links útiles</h4>
                    <ul>
                        <li><i class="bi bi-chevron-right"></i> <a href="{{ url_for('user.user') }}">Home</a></li>
                        <li><i class="bi bi-chevron-right"></i> <a href="https://utacapulco.edu.mx/">Universidad</a>
                        </li>
                        <p class="mt-3"><strong>Phone:</strong> <span>7446886416</span></p>
                        <p><strong>Email:</strong> <span>universidad@utacapulco.edu.mx</span></p>
                    </ul>
                </div>

                <div class="col-lg-4 col-md-4">
                    <h4>Síguenos</h4>
                    <p>Sigue nuestras redes sociales para estar al tanto de las últimas noticias y eventos. Conéctate
                        con nosotros en Facebook e Instagram </p>
                    <div class="social-links d-flex">
                        <a
                            href="https://www.facebook.com/p/Oficial-Universidad-Tecnol%C3%B3gica-de-Acapulco-100063862541593/?locale=es_LA"><i
                                class="bi bi-facebook"></i></a>
                        <a href="https://www.instagram.com/utacapulco/"><i class="bi bi-instagram"></i></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="container copyright text-center mt-4">
            <p>© <span>Copyright</span> <strong class="px-1 sitename">UTA</strong> <span>Todos los derechos
                    reservados</span></p>
        </div>
    </footer>

    <!-- Scroll Top -->
    <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>


    <!-- Vendor JS Files -->
    <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/php-email-form/validate.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/aos/aos.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/glightbox/js/glightbox.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/imagesloaded/imagesloaded.pkgd.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/isotope-layout/isotope.pkgd.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/swiper/swiper-bundle.min.js') }}"></script>

    <!-- Main JS File -->
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>

</html>